### ISSUE TITLE
No drag me option

### ISSUE THREAD

**Issue by harshmahesheka** [gazebosim/docs#230]
I was trying to spawn models from fuel as mentioned in docs- https://ignitionrobotics.org/docs/citadel/fuel_insert but there is no drag me option on the fuel site

**Comment by nkoenig** [comment]
Yes, that is on purpose. It was removed because it stopped working with some version of Ignition. More importantly, Fuel is designed to be used by more than just Ignition, and the button was out of place given that design criteria.

You can spawn models into simulation using the Resource Spawner plugin, or you can copy the SDF snippet from the Fuel website using the button that looks like `<>`.

**Comment by scpeters** [comment]
if the button was removed on purpose, then we need to update the out-of-date tutorials

**Comment by harshmahesheka** [comment]
I would love to contribute; could you please assign this to me.

**Comment by scpeters** [comment]
> I would love to contribute; could you please assign this to me.

thank you!

**Comment by chapulina** [comment]
> It was removed because it stopped working with some version of Ignition. 

I wasn't able to reproduce this issue with any version of Ignition, as demonstrated here: https://gitlab.com/ignitionrobotics/web/app/-/merge_requests/146#note_857910759

> More importantly, Fuel is designed to be used by more than just Ignition, and the button was out of place given that design criteria.

I don't think there was anything in the implementation of the button that was specific to Gazebo. Any application could add drag-drop support if they wanted.

> You can spawn models into simulation using the Resource Spawner plugin

The Resource Spawner is less feature-rich than the Ignition Fuel website when it comes to searching for and inspecting models. I think its only advantage is that it also shows local models. 

> you can copy the SDF snippet from the Fuel website using the button that looks like <>.

That's not convenient when you already have a running simulation.
