### ISSUE TITLE
No debug information for colcon

### ISSUE THREAD

**Issue by onurtore** [gazebosim/docs#245]
## Desired behavior

Giving user additional information related to building with debug mode.

## Alternatives considered

A link to Colcon documentation is given but hard to manage for newcomers.

## Implementation suggestion

I think the right  way is this but I will check that:

`colcon build --cmake-args -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug --merge-install
`

## Additional context

Should I just create a merge request for Garden release or change all of them one by one? Is there any easier method for changing documentation of all the releases?

**Comment by chapulina** [comment]
There are a few tips for building with `colcon` here:

https://ignitionrobotics.org/docs/citadel/install_ubuntu_src#building-the-ignition-libraries

How about adding a note there?

> I think the right way is this but I will check that:

The syntax for combining multiple CMake args that has worked for me in the past is like this:

```
colcon build --cmake-args ' -DBUILD_TESTING=OFF' ' -DCMAKE_BUILD_TYPE=Debug'
```

I have a colcon cheatsheet [here](https://gist.github.com/chapulina/7400a708df655cbfba218e169fcad97f) if it helps.

> Should I just create a merge request for Garden release or change all of them one by one? Is there any easier method for changing documentation of all the releases?

One PR changing all of them is the best way we have now. You only need to update the currently supported / developed ones: Citadel, Fortress and Garden

**Comment by onurtore** [comment]
Hi, 
Thanks for the -cmake-args tip. I also starred your colcon cheatsheet thats very helpful.

**Comment by onurtore** [comment]
ping for a review.
