### ISSUE TITLE
Weird text at the bottom of some tutorials

### ISSUE THREAD

**Issue by caguero** [gazebosim/docs#296]
## Description

I see some weird text in some tutorials ([here](https://gazebosim.org/api/transport/12/services.html), [here](https://gazebosim.org/api/transport/12/messages.html) and [here](https://gazebosim.org/api/transport/12/logging.html)).

**Comment by tejalbarnwal** [comment]
I also found some similar texts at the end [here](https://gazebosim.org/api/math/7/cppgetstarted.html) describing the functions used above on the page.

**Comment by nkoenig** [comment]
Fixed in https://github.com/gazebosim/gz-cmake/pull/314
