### ISSUE TITLE
Broken links on https://gazebosim.org/libs

### ISSUE THREAD

**Issue by peci1** [gazebosim/docs#355]
Most "API & Tutorials" links are dead on https://gazebosim.org/libs .

I've noticed:

- https://gazebosim.org/api/common/5.3/index.html is dead
- https://gazebosim.org/api/common/5/index.html is good

So maybe this page just needs to stop using the minor version in the links?

**Comment by azeey** [comment]
@mabelzhang I think you also noticed this right?

**Comment by mabelzhang** [comment]
Yep

**Comment by traversaro** [comment]
> So maybe this page just needs to stop using the minor version in the links?

I noticed that some libraries work (see https://gazebosim.org/api/fuel_tools/8.0/index.html), but actually link to older version of the documentation instead of the latest one available at https://gazebosim.org/api/fuel_tools/8/index.html .

**Comment by peci1** [comment]
This issue still persists.

**Comment by EyalBrilling** [comment]
Where "https://gazebosim.org/libs" sits? I couldn't find it in this repository(guess because it isn't under gazebosim.org/docs) but quick going over other repositories i didn't find it either.

**Comment by azeey** [comment]
The website is being reworked so it's statically generated, so this will change, but currently it's a being served by the [libs](https://github.com/gazebo-web/gazebosim-web-frontend/blob/main/src/app/libs/libs.component.html) component of the Angular app.

**Comment by azeey** [comment]
Fixed by #441.
