### ISSUE TITLE
`get_started.md` CLI is updated for all version to match Garden

### ISSUE THREAD

**Issue by adamsj-ros** [gazebosim/docs#366]
It appears that this change applied to all versions (including Fortress) for `get_started.md` instructing users to use the command `gz` which doesn't seem to exist after a Fortress install (`ign` does). Am I wrong or does this need to be fixed?

_Originally posted by @adamsj-ros in https://github.com/gazebosim/docs/issues/333#issuecomment-1651926041_

**Comment by azeey** [comment]
The documentation now mentions `ign` if using Citadel or Fortress.
