### ISSUE TITLE
Tutorial layout has issues with narrow windows

### ISSUE THREAD

**Issue by mjcarroll** [gazebosim/docs#384]
I noticed that when resizing a window with the tutorial open, that when the window width is less than approximately ~1000 pixels, then presentation gets a little wonky.

The right side table of contents will start to flow over the edit pencil and the content of the tutorial

![image](https://github.com/gazebosim/docs/assets/279701/139222d7-290b-450f-89a1-5fd50b3d3d22)

When the window gets sufficiently narrow, the content will overflow the window: 
![image](https://github.com/gazebosim/docs/assets/279701/220d74fd-ec60-4652-97db-48095bb407fe).

This makes it difficult to have the tutorial window and the gazebo window/terminal open side-by-side on smaller displays.

**Comment by mabelzhang** [comment]
Should this ticket be in https://github.com/gazebo-web/gazebosim-web-frontend/issues?
Also is the frontend repo automated for the project board?

**Comment by azeey** [comment]
Fixed by #441 
[Screen recording 2024-07-18 13.20.41.webm](https://github.com/user-attachments/assets/3ce22cd4-47b7-4ca0-9911-f91766ad4739)
