### ISSUE TITLE
Installing ros-noetic-ros-gz from packages.ros.org doc

### ISSUE THREAD

**Issue by EyalBrilling** [gazebosim/docs#416]
In the ros/gazebo installtion doc: [https://gazebosim.org/docs/citadel/ros_installation](url) (Notice this is under citadel but the same is true for other versions docs)

It says the following: "To install Gazebo Citadel with Noetic simply install ros-noetic-ros-gz from packages.ros.org."
The problem is,running the following shell command to download it:

```shell
sudo apt-get install ros-noetic-ros-gz
``` 

returns no package is found. Using ubuntu 22.04.
I can think about two reasons:
1) packages.ros.org needs to be sourced to get packages from there.
2) It isn't the right package name and the right name is something like "ros-noetic-ros-ign-gazebo" which i could find. 

It should be much more clear what needs to be done.
Please point me to the right answer and i will fix this.
Thank you.

**Comment by kscottz** [comment]
@EyalBrilling [ROS Noetic binary packages are only available for 20.04](https://wiki.ros.org/noetic/Installation/Ubuntu).
