### ISSUE TITLE
Is the "Ros/gazebo Installation" documentation up to date?

### ISSUE THREAD

**Issue by KomaGR** [gazebosim/docs#456]
Documentation page I have trouble with: https://gazebosim.org/docs/fortress/ros_installation.

I would greatly appreciate a clarification about the information in this page and the steps I have taken.

I will gladly open a PR to update the documentation once I have understood the problem and any suggestions. Thanks in advance.

## Environment
* OS Version: `Linux 6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
* Trying to install from binary

## Description
**I am working on a clean system installation** for the sole purpose of satisfying the recommended system setup of 

> - [Ubuntu Jammy 22.04](https://www.releases.ubuntu.com/jammy/)
> - [ROS 2 Humble Hawksbill](https://www.ros.org/reps/rep-2000.html#humble-hawksbill-may-2022-may-2027)
> - [Gazebo Fortress](https://gazebosim.org/docs/fortress/install)

as mentioned in https://gazebosim.org/docs/harmonic/ros_installation.

I have added the `packages.osrfoundation.org` apt repository by following the instructions [here](https://gazebosim.org/docs/harmonic/install_ubuntu) (up to before `apt-get install gz-harmonic`). 

Then, I:

1. Tried to install the [default Gazebo/ROS pairing](https://gazebosim.org/docs/fortress/ros_installation#installing-the-default-gazebo-ros-pairing) with `ros-humble-ros-gz` (since the recommended setup is with `ROS_DISTRO=humble`). This fails with:

    ```
    Package ros-humble-ros-gz is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source

    E: Package 'ros-humble-ros-gz' has no installation candidate
    ```
2. Indeed, a search yields:
```
$ apt search ros-humble-ros
Sorting... Done
Full Text Search... Done
ros-humble-ros-gzgarden/unknown 0.244.11-1002jammy amd64
  Meta-package containing interfaces for using ROS 2 with Gazebo simulation.

ros-humble-ros-gzgarden-bridge/unknown 0.244.11-1002jammy amd64
  Bridge communication between ROS and Gazebo Transport

ros-humble-ros-gzgarden-image/unknown 0.244.11-1002jammy amd64
  Image utilities for Gazebo simulation with ROS.

ros-humble-ros-gzgarden-interfaces/unknown 0.244.11-1002jammy amd64
  Message and service data structures for interacting with Gazebo from ROS2.

ros-humble-ros-gzgarden-sim/unknown 0.244.11-1002jammy amd64
  Tools for using Gazebo Sim simulation with ROS.

ros-humble-ros-gzgarden-sim-demos/unknown 0.244.11-1002jammy amd64
  Demos using Gazebo Sim simulation with ROS.

ros-humble-ros-gzharmonic/unknown 0.244.12-3jammy amd64
  Meta-package containing interfaces for using ROS 2 with Gazebo simulation.

ros-humble-ros-gzharmonic-bridge/unknown 0.244.12-3jammy amd64
  Bridge communication between ROS and Gazebo Transport

ros-humble-ros-gzharmonic-image/unknown 0.244.12-3jammy amd64
  Image utilities for Gazebo simulation with ROS.

ros-humble-ros-gzharmonic-interfaces/unknown 0.244.12-3jammy amd64
  Message and service data structures for interacting with Gazebo from ROS2.

ros-humble-ros-gzharmonic-sim/unknown 0.244.12-3jammy amd64
  Tools for using Gazebo Sim simulation with ROS.

ros-humble-ros-gzharmonic-sim-demos/unknown 0.244.12-3jammy amd64
  Demos using Gazebo Sim simulation with ROS.
```
So it seems I can install `ros-humble-ros-gzgarden` and `ros-humble-ros-gzharmonic`. **The recommended combination with `gzfortress` does not seem to show up (?).**

3. I decide to install with `ros-humble-ros-gzharmonic` but stumble on the following error:
```
$ sudo apt install ros-humble-ros-gzharmonic
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ros-humble-ros-gzharmonic : Depends: ros-humble-ros-gzharmonic-bridge but it is not going to be installed
                             Depends: ros-humble-ros-gzharmonic-image but it is not going to be installed
                             Depends: ros-humble-ros-gzharmonic-sim but it is not going to be installed
                             Depends: ros-humble-ros-gzharmonic-sim-demos but it is not going to be installed
                             Depends: ros-humble-ros-workspace but it is not installable
E: Unable to correct problems, you have held broken packages.
````
This error indicates that the `ros-humble-ros-workspace` package is not installable. Am I missing a repository?

And I am unsure how to proceed to install a working Gazebo+ROS combination. Perhaps I missed a crucial bit of documentation?

**Comment by azeey** [comment]
Can you check that you have added `packages.ros.org` repository to your apt sources? The instructions in https://gazebosim.org/docs/fortress/ros_installation#installing-the-default-gazebo-ros-pairing assume you have ROS set up already. If not you'd need to that first following https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html
