### ISSUE TITLE
libEGL warning: egl: failed to create dri2 screen for Jetson Orin

### ISSUE THREAD

**Issue by lida2003** [gazebosim/docs#469]
## Environment
* OS Version: Ubuntu 22.04.4 LTS
* Hardware: Jetson Orin Nano 8GB
* JetPack v6.0
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

$ uname -a
Linux nvidia 5.15.136-tegra #1 SMP PREEMPT Mon May 6 09:56:39 PDT 2024 aarch64 aarch64 aarch64 GNU/Linux
```

## Description

"You should see an empty world with just a ground plane and a sun light. " But there is no sun light. BTW, what does sun light mean?

Is there any steps I have missed? Or any update about the document?

PS: [links to Jetson Forum](https://forums.developer.nvidia.com/t/gazebo-building-a-world-demo-libegl-error/301874)

## Steps to reproduce

1. Flash JetPack v6.0
2. Following guide https://gazebosim.org/docs/harmonic/install_ubuntu/ to install  Gazebo Harmonic
3. Following tutorial https://gazebosim.org/docs/latest/building_robot/ to run `gz sim building_robot.sdf`

## Output

```bash
$ gz sim building_robot.sdf
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
```

![图片](https://github.com/user-attachments/assets/2c26f26b-6238-4326-ad13-cb4f397402f1)

--- EDIT: [the finished SDF file for the tutorial](https://github.com/gazebosim/docs/blob/master/harmonic/tutorials/building_robot/building_robot.sdf)

I still didn't find the ground plane and the sun light, but they are in the entity tree at the right bottom of the picture.
![图片](https://github.com/user-attachments/assets/6d3ce711-8327-4111-b5f3-d17f03749833)

**Comment by iche033** [comment]
Hi the libEGL error is found to be harmless, see https://github.com/gazebosim/gz-rendering/issues/587. Currently we don't have a way to prevent our underlying rendering engine from displaying that message. I'll update our docs to explain this.

The ground plane is the grey area that the vehicle sits on. The sun just provides lights to the scene - there is no visual object to represent this. It looks like your gazebo simulation is working fine so I'm closing this issue.
