### ISSUE TITLE
Windows instructions should be updated

### ISSUE THREAD

**Issue by azeey** [gazebosim/docs#483]
As of https://github.com/gazebosim/gz-sim/pull/2382, Gazebo actually runs with Ogre2 on windows, but our [documentation](https://gazebosim.org/docs/latest/install_windows_src/) states that only Ogre (1) is supported. The ["GUI workaround"](https://gazebosim.org/docs/latest/install_windows_src/#gazebo-gui-workaround
) section also mentions that `gz sim -g` does not work.

The [binary](https://gazebosim.org/docs/latest/install_windows/) install instructions also say:
> Additionally, command line tools, the DART physics engine, and some tests are not currently supported in Windows.

which is no longer accurate.

**Comment by azeey** [comment]
@traversaro any help with this would be appreciated.

**Comment by akky20** [comment]
@azeey I have made some changes according to the mentioned point , please have a look . I’m willing to accept any corrections.

1
 ![image](https://github.com/user-attachments/assets/ae535f02-4b13-45b8-9ba5-2dba44bc21da)



2
 ![image](https://github.com/user-attachments/assets/0ca71aa0-ef3a-4cfe-932c-b024c9bde4f2)



3
 ![image](https://github.com/user-attachments/assets/2a3f6847-ad1b-4917-8a0c-6370eb071850)

  Removed the line "Additionally, command line tools..."

**Comment by azeey** [comment]
@akky20 I think would be best if you to go ahead and create a PR with what you have and I'll give my feedback there.

**Comment by akky20** [comment]
> @akky20 I think would be best if you to go ahead and create a PR with what you have and I'll give my feedback there.

Opened the PR , please have a look
