### ISSUE TITLE
Missing libs on docs page

### ISSUE THREAD

**Issue by chapulina** [gazebosim/docs#53]
These pages:

* https://ignitionrobotics.org/docs
* https://ignitionrobotics.org/libs

Are missing ign-tools and ign-cmake.

In a related note, it would be nice to alphabetize them so they're easier to find. In the future we could consider having an icon for each one so they're easier to spot.

**Comment by ahcorde** [comment]
- [x] Alphabetize libraries: https://gitlab.com/ignitionrobotics/web/web/-/merge_requests/14

**Comment by chapulina** [comment]
Generating tutorials for `ign-cmake`: https://github.com/ignitionrobotics/ign-cmake/pull/137

**Comment by mabelzhang** [comment]
Are we excluding `sdformat` from this list? Its tutorial link on https://ignitionrobotics.org/libs is broken.

**Comment by chapulina** [comment]
> Are we excluding sdformat from this list? 

That's being addressed as part of https://github.com/ignitionrobotics/docs/issues/32.

**Comment by azeey** [comment]
Fixed by #441
