### ISSUE TITLE
Make it easy to view tutorials before deploying

### ISSUE THREAD

**Issue by chapulina** [gazebosim/docs#85]
I believe the only way to check locally if the tutorials have all the correct links is to run the site's backend server and frontend static code, which are private. People often assume links, images, embedded HTML will work the same way as on GitHub's preview, and that's not the case.

We need a way for contributors to easily check that their tutorials are rendering correctly before opening a pull request. This should also help reviewers.

This could be viewing the tutorials locally, or deploying a branch to a test URL on every PR / commit.

**Comment by azeey** [comment]
Fixed by #441. It is now possible to build documentation locally. The Github Action workflows also generate the artifacts that can be viewed by PR authors.
